# ███████╗██╗     ███████╗ ██████╗████████╗██████╗  ██████╗ ███╗   ██╗
# ██╔════╝██║     ██╔════╝██╔════╝╚══██╔══╝██╔══██╗██╔═══██╗████╗  ██║
# █████╗  ██║     █████╗  ██║        ██║   ██████╔╝██║   ██║██╔██╗ ██║
# ██╔══╝  ██║     ██╔══╝  ██║        ██║   ██╔══██╗██║   ██║██║╚██╗██║
# ███████╗███████╗███████╗╚██████╗   ██║   ██║  ██║╚██████╔╝██║ ╚████║
# ╚══════╝╚══════╝╚══════╝ ╚═════╝   ╚═╝   ╚═╝  ╚═╝ ╚═════╝ ╚═╝  ╚═══╝
#                       Practice • v1.7.2

MONGO:
  URI: "mongodb://127.0.0.1:27017"
  DATABASE: "electron"

SETTINGS:
  # ↓ Spawn Cords (/setspawn works)
  SPAWN-LOCATION: "world, 0, 150, 0, 0, 0"
  # ↓ Would you like a Join MOTD?
  JOIN-MESSAGE:
    ENABLED: true
    TEXT:
      - " "
      - "&b&lElectron Practice"
      - " &7Duels, events, ranked"
      - " &7Multiple game modes available"
      - " "